name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: build cpp
        working-directory: ./cpp
        run: make
